apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scale-test
    version: "1.0"
  name: app-2-n
  namespace: mesh-scale
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: scale-test
      app.index: application-1
      app.variant: stable
      deploymentconfig: app-2
      version: "1.0"
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      annotations:
        sidecar.istio.io/concurrency: "1"
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPU: 200m
        sidecar.istio.io/proxyCPULimit: 1000m
        sidecar.istio.io/statsInclusionPrefixes: listener,cluster.outbound
      creationTimestamp: null
      labels:
        app: scale-test
        app.index: application-1
        app.variant: stable
        deploymentconfig: app-2
        version: "1.0"
    spec:
      containers:
      - env:
        - name: NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: VARIANT
          value: canary
        - name: JAVA_OPTIONS
          value: |
            -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory
        image: quay.io/cfilleke/mannequin:0.0-z
        imagePullPolicy: Always
        name: mannequin
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 300m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/certs
          name: certs
      dnsPolicy: ClusterFirst
      nodeSelector:
        test.role: workload
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: workload
        operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: scale-test
        maxSkew: 1
        topologyKey: workload
        whenUnsatisfiable: ScheduleAnyway
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: app-1
  test: false
  triggers:
  - type: ConfigChange