apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: envoyproxy/nighthawk-dev:latest 
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
